### ISSUE TITLE
[EPIC] Coffee Chat Feature

### ISSUE THREAD

**Issue by kallentu** [uwcsc/codeybot#23]
**Tasks**
- [x] Write/translate algorithm that matches coffee chat members.
- [x] Handle the case where all matches have met each other at least once before.
- [x] DM matches their match result and write a short introduction.
- [x] Provides mods a summary of match results, preferably showing the number of times the pair has met before.
- [x] Improve documentation and readability of the matching algorithm.
- [x] Run simulations to get data and gain more confidence in the algorithm.
- [x] Implement a mod command to start the matching process and send the mod match results for approval.
- [ ] #83

**Is your feature request related to a problem? Please describe.**
The problem is finding a way to add more 1:1 connections in our community that is external to the executive committees. I want to be able to meet other people and have deeper conversations with them than speed-friending/afterhours events.

**Describe the solution you'd like**
Not sure if this is a command, but it would be nice to have something working like the Donut bot in Slack, where we can run it every [week/month], the opted-in people (through emojis or buttons probably) would be able to coffee chat with someone new. The bot would match them and maybe send each person the Discord id + tag so they can meet up.

I feel like this has been done by some Discord bot somewhere, so probably need a quick search first.

If not feasible, it's fine, I just thought this would be a cool thing to have on the Discord.

**Additional context**
https://www.donut.com/ for those that don't know what I'm talking about.

**Comment by gzcharleszhang** [comment]
Yeah this is a good idea. I think we could implement a (set of) command(s) that opts people in/out of weekly matchings. We could handle this one of two ways:
1. store all of the people who opted-in in our own DB.
2. give people who opted-in a new role, and when we match we just query for users that have this role.

If we do option #2, users could see who's in the matching program and who's not, and we could also create a text channel that only people who opted-in can see, to manage notifications or to act as a platform for them to talk about/give feedback regarding this feature.

**Comment by kallentu** [comment]
I am also unsure about what Discord bots can handle.
I think it might be cool to have a private text channel for the Coffee Chat role and then codey can ping the two people in a post so you can easily find the person you're matched with. Otherwise private DM is better.
